### ISSUE TITLE
Can not access

### ISSUE THREAD

**Issue by paipaipaipai** [bitclout/run#10]
![image](https://user-images.githubusercontent.com/30950645/115841644-9559e400-a44f-11eb-941b-768aa6d32603.png)

**Comment by tijno** [comment]
You have to use a domain - wont work with IP.

README.md suggests using http://bitclout.me if running node locally.

**Comment by paipaipaipai** [comment]
in /etc/hosts
i set 
![image](https://user-images.githubusercontent.com/30950645/115846924-fa640880-a454-11eb-93be-037069dcc3c5.png)
Then visit bitclout.me, it's still useless

**Comment by tijno** [comment]
Also need to see api.bitclout.me 

Although readme suggests you should not need to manually set it in hosts - but it wont hurt.

**Comment by connerdouglass** [comment]
Hey @paipaipaipai! You definitely want to keep your `/etc/hosts` file the way it was before, with the "127.0.0.1 localhost" entry. You shouldn't need to edit it to run a node.

"bitclout.me" was setup by the BitClout developers, and it automatically points to your `127.0.0.1` localhost address without you needing to do anything.

**Comment by jazzyjackson** [comment]
Your hosts file ain't gonna do it because hosts file doesn't let you specify ports

follow the readme

**Comment by paipaipaipai** [comment]
> Hey @paipaipaipai! You definitely want to keep your `/etc/hosts` file the way it was before, with the "127.0.0.1 localhost" entry. You shouldn't need to edit it to run a node.
> 
> "bitclout.me" was setup by the BitClout developers, and it automatically points to your `127.0.0.1` localhost address without you needing to do anything.
This is what I use 127.0.0.1
![image](https://user-images.githubusercontent.com/30950645/115849900-ed94e400-a457-11eb-9f1f-b06862adaddb.png)

**Comment by paipaipaipai** [comment]
There are a lot of bugs, so I can’t use it

**Comment by Rhys-Woolcott** [comment]
> There are a lot of bugs, so I can’t use it

Dont use this. It is a scam
