### ISSUE TITLE
Unable to Sync Node 

### ISSUE THREAD

**Issue by AroraShreshth** [bitclout/run#17]
## Syncing stuck with this output being thrown repeatedly for 30 minutes .

<img width="1679" alt="Screenshot 2021-04-24 at 2 22 32 AM" src="https://user-images.githubusercontent.com/43671435/115928549-edbad100-a4a3-11eb-8ea1-2d1e1dde3a36.png">

**_CONNECT_IPS flag in dev.env set to bitclout-seed-2.io_**

**_IGNORE_INBOUND_PEER_INV_MESSAGES set to true_**

**Comment by jlevy-dev** [comment]
I am having this same issue as well... if anyone has a solution I would greatly appreciate it. :)

**Comment by chafreaky** [comment]
Make sure you allocate enough RAM to your docker. Syncing process is very intensive. I launched mine with 32gb during syncing, I am able to scale down afterwards as it's less resource intensive. This is due to the index map being built when syncing.

**Comment by jlevy-dev** [comment]
Alright, thank you! I will see if I can make my node have more ram.

**Comment by pangia** [comment]
> Make sure you allocate enough RAM to your docker. Syncing process is very intensive. I launched mine with 32gb during syncing, I am able to scale down afterwards as it's less resource intensive. This is due to the index map being built when syncing.

32gb worked. thank you!

**Comment by maebeam** [comment]
Reopen if more ram doesn't help. Thanks!

**Comment by AroraShreshth** [comment]
Yeah more ram helped 😌
