### ISSUE TITLE
Unable to login to bitclout.me with original account.

### ISSUE THREAD

**Issue by UnknownNFT** [bitclout/run#19]
Hi everyone, hope this isn't just an issue I'm experiencing. When I attempt to log in to my main UnknownNFT account, it just spits me back to the homepage and doesn't actually log me in.

**UPDATE**
I've been able to edit my dev.env file to add my admin public key, which I believe has resolved my problem as I'm able to fully log in and see the proper syncing of the headers and blocks :)

![image](https://user-images.githubusercontent.com/83103574/115944342-132ae900-a46a-11eb-9405-284b2a202246.png)

![image](https://user-images.githubusercontent.com/83103574/115944364-2c339a00-a46a-11eb-8eae-136fe78bade6.png)

I do have the node fully up and running and it did actually work momentarily and I could access the admin panel.

I also managed to get some kind of error when trying several times to log in:

![unknownerror](https://user-images.githubusercontent.com/83103574/115944423-80d71500-a46a-11eb-9c54-517d687cb677.png)

Any help would be greatly appreciated! :)

**Comment by chafreaky** [comment]
The "Fetching..." message at the top of your home page indicates there is an issue accessing your API (it's unable to get the /get-exchange-rate endpoint).

Check that you're not getting any CORS errors when landing on your node and that you have properly edited your Caddyfile.dev

**Comment by jcmaciel** [comment]
I have the same problem here, I believe I am connected to the core, because I received this error message "core exited with code 137"

**Comment by jcmaciel** [comment]
To fix: Increase memory limit on your Docker options

**Comment by UnknownNFT** [comment]
> The "Fetching..." message at the top of your home page indicates there is an issue accessing your API (it's unable to get the /get-exchange-rate endpoint).
> 
> Check that you're not getting any CORS errors when landing on your node and that you have properly edited your Caddyfile.dev

Thanks for the reply!! I did see one core error which was the following:
E0424 16:35:58.539491       1 dkAK5MoX.go:1] ReadBitCloutMessage: : ReadMessage: Problem decoding NetworkType: EOF

I'm a bit new to this as well, when you asked if I've properly edited my Caddyfile.dev, I have not yet done this. I didn't happen to see anything in the posting about this. Do you mind elaborating on that part a bit, what would I need to edit? :)

**Comment by UnknownNFT** [comment]
> To fix: Increase memory limit on your Docker options

Going to give this a try!

**Comment by maebeam** [comment]
Reopen if more ram doesn’t help!

**Comment by UnknownNFT** [comment]
Thank you maebeam! :)
