### ISSUE TITLE
When I request '/api/v1/transaction-info',I get the error :"net::ERR_CONNECTION_REFUSED"

### ISSUE THREAD

**Issue by wintroner** [bitclout/run#23]
I create a node ,When I request '/api/v1/transaction-info',I get the error :"net::ERR_CONNECTION_REFUSED",this issues waste much time,I don't know how to set,Anybody can help me, please!

my setting: MAX_BLOCK_TEMPLATES_TO_CACHE=0,read-only

**Comment by apolo423** [comment]
Hey @wintroner .
When I use this endpoint, I met follow issue.  
{
    "Error": "UpdateTxindex: Error connecting txn: < TxHash: b7d6f0a31a4f083c98c5837ca3f4b929bbec0d00150bf6eb4753b6ce05e5d5e5, TxnType: BC1YLj8LiXjYeH1mT98sjyKMzD3ebMMQxdQHnFy1Y6o8coMii4rq7Az, PubKey: FOLLOW >: UpdateTxindex: Error connecting txn to UtxoView: ConnectTransaction: : _connectFollow: : RuleErrorInputSpendsNonexistentUtxo"
}

Do you know why and how to fix? Originally it worked well, but suddenly this issue occured. :-(
