### ISSUE TITLE
issue  reading google application credentials 

### ISSUE THREAD

**Issue by dezzyboy** [bitclout/run#24]
setting relative path in dev.env for google credentials results into this :
Error validating body bytes: SubmitPost: Error uploading images: dialing: cannot read credentials file: open /home/username/credentials.json: no such file or directory

i see that there is an "open" before the path could this be it?

**Comment by maebeam** [comment]
Are you setting `GOOGLE_APPLICATION_CREDENTIALS_PATH`?

**Comment by dezzyboy** [comment]
es i have set it with absolute path in dev.env  to where my google json credentials is located  `GOOGLE_APPLICATION_CREDENTIALS_PATH=/home/user/credentials.json`

**Comment by maebeam** [comment]
You need to mount the credentials file in the docker image. If you need more help I'd suggest joining the discord. There's a link in the readme.
