### ISSUE TITLE
The core keeping stop for no reason

### ISSUE THREAD

**Issue by thaodx** [bitclout/run#27]
The core always stops after few minutes.
![alt text](https://i.imgur.com/paE3Xvp.png "Core log")

**Comment by maebeam** [comment]
Did you give your docker container enough memory?

**Comment by thaodx** [comment]
> Did you give your docker container enough memory?

I was allocated 4GB memory, is it enough?

**Comment by tijno** [comment]
see the FAQ:

https://docs.bitclout.com/devs/running-a-node#what-are-the-minimum-requirements-for-syncing-a-node

32gb
