### ISSUE TITLE
Uploading profile failed

### ISSUE THREAD

**Issue by jsemrau** [bitclout/run#31]
In the logs I observe regularly the following:

Datadog Tracer v1.29.0 ERROR: Uploading profile failed: Post "http://localhost:8126/profiling/v1/input": dial tcp 127.0.0.1:8126: connect: connection refused. Trying again in 22.735594653s..., 1 additional messages skipped (first occurrence: 29 Apr 21 13:14 UTC)
2021/04/29 13:15:26 Datadog Tracer v1.29.0 ERROR: Failed to upload profile: failed after 2 retries, last error was: Post "http://localhost:8126/profiling/v1/input": dial tcp 127.0.0.1:8126: connect: connection refused

Not sure what the app is trying to do and why it doesn't work.

**Comment by tijno** [comment]
i believe this is for their own internal logging / monitoring on main bitclout and has not been removed for self hosted nodes.

**Comment by jsemrau** [comment]
Doesn't help when you are debugging your own nodes, though. Because it keeps you wondering if that is related to a misconfiguration on your end or not.

**Comment by tijno** [comment]
For sure - i cant wait for them to just release the source for core and let the community help with PRs of small changes like that.

**Comment by maebeam** [comment]
We will add a flag to make tracing optional

**Comment by dgsus** [comment]
@maebeam  could you perhaps add a option for elasticsearch apm too? or other opensource one you find worthy. 
thx!

**Comment by maebeam** [comment]
Tracing is now optional and disabled by default
