### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by mywebpower** [bitclout/run#35]
node segfaults randomly while syncing

I0502 16:45:20.628398       1 kbkPdUd7.go:1] Server._handleTransactionBundle: Found 0 BitcoinExchange txns that were double-spends!
I0502 16:45:20.630483       1 E2539Jcv.go:1] Server._handleTransactionBundle: Accepted 5 txns from Peer [ Remote Address: 104.238.183.241:17000 PeerID=124 ]
E0502 16:45:21.123435       1 C4lzFMjk.go:1] ReadBitCloutMessage: : ReadMessage: Problem decoding NetworkType: EOF
E0502 16:45:21.123475       1 b1qbZ81P.go:1] _connectPeer: Problem negotiating version with peer with addr: (10.8.12.108:8543) err: (negotiateVersion: Problem reading INBOUND peer version for Peer [ Remote Address: 10.8.12.108:8543 PeerID=2706 ]: readVersion: : ReadBitCloutMessage: : ReadMessage: Problem decoding NetworkType: EOF)
I0502 16:45:21.199448       1 tD3yQjnW.go:1] RECEIVED( seq=1817 ) message of type: INV from peer [ Remote Address: 178.63.32.75:17000 PeerID=479 ]: Num invs: 5, SyncResponse: false, InvList: [Type: TX_INV, Hash: b6f8b540d0e806de298b071dbd54f44d25ef7fc00aecbb98732b3717856803ad Type: TX_INV, Hash: bd44283afe134f7d55e70dcafbb806ae52ccd6c6a8a9efa36df89ec3ecca3dd4 Type: TX_INV, Hash: a49e608057e9bd4fe58e562e0f01919150a73701ce2da5645410bbd9512a74b1 Type: TX_INV, Hash: d49b6dc7a9b84994df7dcac7408158f1fd9aef2b0fd457453f9c38326e986d6f Type: TX_INV, Hash: 6a5614aa1ad9e8d21af305ae8864b767f501ef6989ea3b93f0e322cf644f7ace]
I0502 16:45:21.204520       1 Gm24JbqZ.go:1] StartBitCloutMessageProcessor: RECEIVED message of type INV with num hashes 5 from peer [ Remote Address: 178.63.32.75:17000 PeerID=479 ]
I0502 16:45:21.204557       1 S_Jxg4Om.go:1] Server._handleInv: Processing INV message of size 5 from peer [ Remote Address: 178.63.32.75:17000 PeerID=479 ]
I0502 16:45:21.204612       1 vIYiLWeB.go:1] Server._handleInv: Not sending GET_TRANSACTIONS because no new hashes
I0502 16:45:21.215827       1 Jx1BfN_x.go:1] Server._relayTransactions: Mempool view has regenerated
I0502 16:45:21.257348       1 rvFyTp0F.go:1] Server._relayTransactions: Relay to all peers is complete!
I0502 16:45:21.257371       1 XhDCQEJ4.go:1] Server._relayTransactions: Waiting for mempool readOnlyView to regenerate
E0502 16:45:21.684525       1 C4lzFMjk.go:1] ReadBitCloutMessage: : ReadMessage: Problem decoding NetworkType: EOF
E0502 16:45:21.684566       1 b1qbZ81P.go:1] _connectPeer: Problem negotiating version with peer with addr: (10.8.12.108:34813) err: (negotiateVersion: Problem reading INBOUND peer version for Peer [ Remote Address: 10.8.12.108:34813 PeerID=2707 ]: readVersion: : ReadBitCloutMessage: : ReadMessage: Problem decoding NetworkType: EOF)
I0502 16:45:21.747026       1 tD3yQjnW.go:1] RECEIVED( seq=4991 ) message of type: INV from peer [ Remote Address: 104.238.183.241:17000 PeerID=124 ]: Num invs: 2, SyncResponse: false, InvList: [Type: TX_INV, Hash: ce6ac5439f1807265b969290345ec618003b53f10993982a0e9c6db09638fcf7 Type: TX_INV, Hash: 5c30df3ab42ec3f685eef5b2bc230c50a59a22ed5cc34787edee248c91e8be46]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10f08f6]

goroutine 49683 [running]:
kY5Mrtid.GUHSO8lz(0x0, 0x89ffffffffffffff)
	CmVzKbMq.go:1 +0x36
kY5Mrtid.(*BlockHash).String(0x0, 0xc3bdb92150, 0x136eb1b)
	v4Tz3fpG.go:1 +0x2f
kY5Mrtid.FICRai_5(0xc4fd70d7f8)
	Ji454JBg.go:1 +0x1af2
kY5Mrtid.MZ1OwSEE(0xc062930140, 0x0, 0x0, 0x1)
	BFzbDghm.go:1 +0x34cb
kY5Mrtid.(*SyncingService).Start.func1(0xc15b7fa680, 0x0, 0x0)
	H2KyrdcH.go:1 +0x1ee
github.com/dgraph-io/badger/v3.(*DB).View(0xc0005b3800, 0xc061947f60, 0x0, 0x0)
	github.com/dgraph-io/badger/v3@v3.2011.1/txn.go:800 +0x95
kY5Mrtid.(*SyncingService).Start(0xc4fd70df88)
	OabLXZrx.go:1 +0xe6
main.main.func3(0xc0005b3800)
	q3kDz99k.go:1 +0xb3
created by main.main
	xzTz5LIn.go:13 +0x199f

**Comment by maebeam** [comment]
This should be fixed now
