### ISSUE TITLE
Nodes stuck at Block 20891

### ISSUE THREAD

**Issue by tijno** [bitclout/run#36]
Looks like self hosted nodes are stuck at this block.

See admin output below.

![20210504-QquTdRGX](https://user-images.githubusercontent.com/69529928/116988182-f1323180-acc7-11eb-8293-e387f4242145.png)

Main explorer is at 21065.

Other nodes also stuck at 20891 - [see Discord](https://discord.com/channels/820740896181452841/835273317773869086/839035062997614632)

**Comment by chafreaky** [comment]
I can confirm, same here. Fully synced status and last block being 20891.

**Comment by salilsethi** [comment]
Same issue.

**Comment by mvanhalen** [comment]
I have seen a similar issue and many of these messages on the recommended peers. With no mining and recommended settings for node syncing issues.

The error message:Problem negotiating version with peer with addr: (104.238.183.241:17000) err: (negotiateVersion: Problem reading OUTBOUND peer version for Peer [ Remote Address: 104.238.183.241:17000 PeerID=10 ]: readVersion: : ReadBitCloutMessage: : ReadMessage: Problem decoding NetworkType: EOF)

telnet to this ip and port works.

**Comment by maebeam** [comment]
Hey all, we made some consensus changes that seem to have some nodes stuck. We're working on this now

**Comment by maebeam** [comment]
Make sure you pull the latest core-obf image to get the consensus changes and then your node should resume syncing. Let me know if this isn't the case.
