### ISSUE TITLE
Errors connection recommended sync node

### ISSUE THREAD

**Issue by mvanhalen** [bitclout/run#39]
I'm getting these errors and my core container crashes each time. Tried it multiple times

Seeing these errors.
_connectPeer: Problem negotiating version with peer with addr: (104.238.183.241:17000) err: (negotiateVersion: Problem reading OUTBOUND peer version for Peer [ Remote Address: 104.238.183.241:17000 PeerID=10 ]: readVersion: : ReadBitCloutMessage: : ReadMessage: Problem decoding NetworkType: EOF)

telnet to this ip and port works

have set the recommend node sync settings when having issues.

**Comment by tijno** [comment]
I pulled chaines from main and updated containers - only had 2 `Problem reading OUTBOUND peer` errors show and blocks sync. So your issue may be resolved too ones you update.

**Comment by mvanhalen** [comment]
> I pulled chaines from main and updated containers - only had 2 `Problem reading OUTBOUND peer` errors show and blocks sync. So your issue may be resolved too ones you update.

I tried the last version. Still some issues. Might be machine related. Testing on another machine as well later. Will follow up.

**Comment by mvanhalen** [comment]
I upped my machine specs in Azure and now it´s properly syncing. I had 2 vpu 4GB. Now 4vpu 16 GB and it´s behaving a lot better
