### ISSUE TITLE
Go crypto/ecdsa verification for admin public keys

### ISSUE THREAD

**Issue by connerdouglass** [bitclout/run#4]
When the node is configured to use a whitelist of admin public keys (to restrict access to the Admin tab), we're getting an error from the core when attempting to access the Admin tab.

The website backend / core is returning a HTTP 400 error with this response body for all of the admin-protected endpoints:
```json
{"error":"CheckAdminPublicKey: Invalid token: crypto/ecdsa: verification error"}
```

And the usual error dialog on the frontend:

<img width="1250" alt="Screen Shot 2021-04-22 at 10 57 27 PM" src="https://user-images.githubusercontent.com/3151515/115825705-aad2fd80-a3be-11eb-853f-5164914a4572.png">

If this is a bug, it exists in the "core" Go project somewhere. As that isn't open sourced yet, I'm reporting the issue here!

**Comment by thealialexander** [comment]
Thanks, Conner.

**Comment by connerdouglass** [comment]
Also, here is the relevant section in our `dev.env` file:

```
# admin_public_keys is list of public keys delimited by commas or new-lines
# which gives users access to the admin panel. If no keys are specified
# anyone can access the admin panel. You can add a space and a comment after
# every public key and leave a note about who the public key belongs to.
ADMIN_PUBLIC_KEYS=BC1YLhK3ouVX5pp53UfqzXYdoM3fUFL8ewsdeGifVTvpVMu4CBB3hwS

```

**Comment by LvlUpGuy** [comment]
Can report that I am seeing the same issue here.

My dev.env file is similar to @connerdouglass with key appearing without spaces and without comment.

**Comment by chafreaky** [comment]
I am able to run a node with admin access smoothly with no errors. What is your infra / config on this one?

**Comment by maebeam** [comment]
You might have accessed an outdated version of the identity service. If you re-authenticate with identity and/or clear your caches does it work?

**Comment by AroraShreshth** [comment]
Facing the same issue this side can't access admin panel in self hosted node.

**Comment by maebeam** [comment]
Hm, thanks for the reports all. I will investigate

**Comment by LvlUpGuy** [comment]
> You might have accessed an outdated version of the identity service. If you re-authenticate with identity and/or clear your caches does it work?

Can confirm that this did not resolve the issue currently. All other elements seem to be working. Had my node running all day and can't wait to get more access for even more exploration. Thank you.

**Comment by AroraShreshth** [comment]
Hey did anyone try another browser for this issue. I  think so the frontend is getting cached. mine worked when changing the browser

**Comment by mywebpower** [comment]
Where is the repo for: ghcr.io/bitclout/core-obf:latest, ghcr.io/bitclout/frontend:latest

**Comment by AroraShreshth** [comment]
> Where is the repo for: ghcr.io/bitclout/core-obf:latest, ghcr.io/bitclout/frontend:latest

Not yet open sourced

**Comment by smartmanru** [comment]
Error global params: CheckAdminPublicKey: Invalid token: crypto/ecdsa: verification error
On the latest version (1963c227bc827e5142a15cca5b5fad5ac0494f50) , with the new identification does not work public key, works only if you leave the field empty... What version of openssl do you use?

**Comment by maebeam** [comment]
I believe this is fixed. Please reopen if you're still experiencing this issue.
