### ISSUE TITLE
Nodes stuck at 21298

### ISSUE THREAD

**Issue by tijno** [bitclout/run#41]
Following fix of #36 - and updating node to `stable` core/frontend - sync worked but has now again stopped at 21298 whereas chain is at 21354

**Comment by tijno** [comment]
![20210505-Zy60UwiR](https://user-images.githubusercontent.com/69529928/117124288-0d99a100-ad90-11eb-99c5-a538f2d52bdb.png)

Looks like its started syncing again

**Comment by arnoldojqf** [comment]
I'm also stuck at block 21373, have already run issue #36 and the problem was not solved.

**Comment by tijno** [comment]
I cleared my volume and restarted container to trigger resync. Doing much better - Fully Synced at block 21693. Just the TSIndex taking ages but thats normal.

**Comment by tijno** [comment]
ok all sorted. node is syncing to latest block with TxIndex matching too. Closing this issue.

**Comment by marshj1977** [comment]
Not sure why this is closed - still seems to be an issue (well not this specific block).
I've reset everything set recommended sync problems settings.

reset a number of times now and it still gets stuck with blocks remaining ever increasing.
