### ISSUE TITLE
Coin purchasers/receivers dont show coins

### ISSUE THREAD

**Issue by tijno** [bitclout/run#46]
[This PR](https://github.com/bitclout/frontend/pull/41) does not seem to work correctly on self hosted nodes. Looks like `"HasPurchased": false` is returned for all `UsersYouHODL` apart from the user themselves. 

Bitclout:

![20210509-g4K8NeyY](https://user-images.githubusercontent.com/69529928/117567251-4baa0400-b0b3-11eb-930f-76b6dc7a519b.png)

My node:

![20210509-iimtP9je](https://user-images.githubusercontent.com/69529928/117567253-4f3d8b00-b0b3-11eb-89ae-ee879606b10b.png)

**Comment by maebeam** [comment]
@tijno unfortunately, you will need to re-sync your node from scratch to get the correct value for `HasPurchased`. if that doesn't fix it let me know.

**Comment by tijno** [comment]
thx @maebeam - just completed re-sync and its resolved now.
