### ISSUE TITLE
Exchange Listing API doesn't work?

### ISSUE THREAD

**Issue by lobovkin** [bitclout/run#52]
Can't transfer BitClout using a public/private key-pair.
The transaction does not leave my node.

**Comment by tijno** [comment]
My understanding - Nodes cant issue transactions to the main chain yet. They will stay in mempool and will disappear at some point as they are removed after not being picked up in a block.

**Comment by lobovkin** [comment]
Yes, it looks like it. Then I do not understand why there is documentation on this API, if it can not yet be used in full. And why it is not specified in the documentation.

**Comment by maebeam** [comment]
The API works, the chain will be accepting transactions from any node very soon.
