### ISSUE TITLE
Error loading shared library libvips.so on Latest

### ISSUE THREAD

**Issue by tijno** [bitclout/run#54]
Core container starts but then exits immediately with these errors, when using `latest` [83b2843a2a059a7cb47a49475acd507bec9d22af](https://github.com/orgs/bitclout/packages/container/core-obf/2543730?tag=83b2843a2a059a7cb47a49475acd507bec9d22af)

```
core        | Error loading shared library libvips.so.42: No such file or directory (needed by /core/backend)
core        | Error loading shared library libgobject-2.0.so.0: No such file or directory (needed by /core/backend)
core        | Error loading shared library libglib-2.0.so.0: No such file or directory (needed by /core/backend)
core        | Error relocating /core/backend: vips_cache_drop_all: symbol not found
core        | Error relocating /core/backend: vips_object_print_all: symbol not found
```

**Comment by tijno** [comment]
seems core image is missing vips. When adding it with `apk add vips` backend starts without issues.

**Comment by tijno** [comment]
Workaround

1. Create folder `core` in your run repo folder

2. In core folder add `Dockerfile` with the following 2 lines:

```
FROM ghcr.io/bitclout/core-obf:latest
RUN apk add vips
```

3. Amend `docker-compose.dev.yml` under `core:` service, change:

`image: ghcr.io/bitclout/core-obf:latest`

to

`build: ./core`

4. Start containers fresh

```
docker-compose -f docker-compose.dev.yml build --no-cache --pull
docker-compose -f docker-compose.dev.yml up -d
```

**Comment by maebeam** [comment]
We recommend using the stable tag

**Comment by tijno** [comment]
yep aware and running both stable and latest. Let me know if not helpful to post bug report on latest @maebeam.
