### ISSUE TITLE
Core API on port 17001 stopped work

### ISSUE THREAD

**Issue by lobovkin** [bitclout/run#56]
`curl --header "Content-Type: application/json" --data-raw '{}'     http://localhost:17001/api/v1/node-info`
`curl: (56) Recv failure: Connection reset by peer`

There were no changes, just stopped working a few hours ago. Restarting with downloading the container update does not help.

**Comment by tijno** [comment]
same for me on latest - stable is fine.

**Comment by maebeam** [comment]
Please use stable, there are breaking changes on latest

**Comment by maebeam** [comment]
Fixed
