### ISSUE TITLE
Getting an error when I set the ADMIN_PUBLIC_KEYS to my public key

### ISSUE THREAD

**Issue by payini** [bitclout/run#68]
When I set my public key to the ADMIN_PUBLIC_KEYS field in the dev.env I get the error below.

I have tried clearing the cache. Setting 1 public key, multiple separated by commas, and one per line. No matter what I get the error.

Oops...
Error global params: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":502,"statusText":"Bad Gateway","url":"http://13.77.183.42/api/v0/admin/get-global-params","ok":false,"name":"HttpErrorResponse","message":"Http failure response for http://13.77.183.42/api/v0/admin/get-global-params: 502 Bad Gateway","error":"<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.21.0</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n"}

![image](https://user-images.githubusercontent.com/2638642/124396754-5dc5ae80-dcc0-11eb-8577-d4dd36ab5127.png)

**Comment by maebeam** [comment]
You should be seeing an exception in the server logs. If you could share that it would be helpful!

**Comment by payini** [comment]
Hello @maebeam, thanks for your response.

Some extra information.

I am running the node, in a Docker container in an Ubuntu machine.
I checked the nginx, frontend and backend logs, and I can't find any exception information about the error.

If I set the ADMIN_PUBLIC_KEY the admin page fails, if I remove my public key the admin pages works, but obviously for all users.

What kind of server logs, are you suggesting for me to look at?

Thanks again.

**Comment by tijno** [comment]
@payini are you using Brave browser ? If so can you try in Safari, Edge or Chrome ?

I have this issue with Brave.

Re logs - the nginx container logs should show a non 200 http code line when access admin.

But i think the one that maebeam is asking for are the logs from backend container.

You should be able to use (from memory, am on mobile) 

`docker logs --follow backend`

then access the admin section and watch for error output - most likely a trace.

**Comment by maebeam** [comment]
I just looked into this and it seems that Identity is returning an empty or invalid JWT token.

Like @tijno mentioned, are you running Brave or Edge? Identity is currently slightly broken on those browsers

**Comment by payini** [comment]
I am not using Brave, I am using Chrome and Edge. Latest versions for both. It seems the issue actually happens in Edge to. I went to Chrome and tested there, and I'm not getting the error there, at the moment.

**Comment by maebeam** [comment]
Yep this is an issue with Identity. Tracking here: https://github.com/bitclout/identity/issues/46

**Comment by payini** [comment]
Got it. Thanks for the help!
