### ISSUE TITLE
Adding comma separated list of Admins  or newline not working

### ISSUE THREAD

**Issue by AdonousTech** [bitclout/run#71]
When I add more than one public key to `ADMIN_PUBLIC_KEYS`  flag in `dev.env` it doesn't recognize the additional keys. 

This doesn't work for me:
ADMIN_PUBLIC_KEYS=somepubkey1,somepubkey2

Am I missing something?

**Comment by maebeam** [comment]
Right now only spaces are supported as separators. Adding support for other separators or updating the documentation would be great

**Comment by AdonousTech** [comment]
Ahh, ok. Thanks! I was scratching my head on this one. Appreciate it!

**Comment by tijno** [comment]
See  #72 with fix to dev.env comments

**Comment by maebeam** [comment]
Thank you tijn!
